implement gallery
squiel91/secondly pull request #3
Opened 2021-01-21 10:16 UTC by manoranjannayak

Hello @squiel91 

Please check the PR and let me know of any changes.

2021-01-21 12:05 UTC, squiel91 requested changes
Please review the commented code and update the PR.

2021-01-21 12:05 UTC, squiel91 commented on models/Image.js
> +  name: {
I would write it in one line, the same as atl, to be consistent

2021-01-21 12:05 UTC, squiel91 commented on controllers/gallery-controller.js
> +    Image.findByIdAndUpdate(id,{$set:{name: imageName, alt: imageAlt}},{new:true, upsert:true}).then((data)=>{
I would do it with async await. Use it wherever is possible.

2021-01-21 12:05 UTC, squiel91 commented on controllers/gallery-controller.js
> +        res.send(data)
Why send and not json?

The res.send function sets the content type to text/Html which means that the client will now treat it as text. It then returns the response to the client.

The res.json function on the other handsets the content-type header to application/JSON so that the client treats the response string as a valid JSON object. It also then returns the response to the client.

2021-01-21 12:05 UTC, squiel91 commented on controllers/gallery-controller.js
> +        res.send(data)
Why send and not json?

2021-01-21 12:05 UTC, squiel91 commented on routes/gallery-routes.js
> +router.patch("/:id", galleryController.patchGallery)
would change it to imageId to be consistent with the rest of the code.

[resouceName]Id

2021-01-21 12:05 UTC, squiel91 commented on controllers/gallery-controller.js
> +        return res.redirect("gallery")
**Rememeber this is an API**, you should return the new resource
const newImage = await image.save()
[no need for return] res.json({success: true, image: newImage})

2021-01-21 12:05 UTC, squiel91 commented on controllers/gallery-controller.js
> +        res.send(data)
No need to send data back, just a json {success: true} is enough.

2021-01-21 12:05 UTC, squiel91 commented on controllers/gallery-controller.js
> +        res.render("gallery/gallery.ejs",{datas})
Good! GET is the only one that renders a page.

2021-01-21 12:05 UTC, squiel91 commented on views/gallery/gallery.ejs
> +      action="/gallery?_csrf=<%= csrfToken %>"
This will have to be done programmatically with AJAX, attaching an event onchange onto the file input, can not reload the page. It waits until it gets a response and then add the new image to the gallery container. Sorry I wasn't clear enough.

2021-01-21 12:05 UTC, squiel91 commented on views/gallery/gallery.ejs
> +  <% for (let data of datas) { %>
Great! Just to be consistent with the rest, instead of "datas" pass "images" to the view and use

images.forEach(image => {
...
})

2021-01-21 12:05 UTC, squiel91 commented on upload/index.js
> +    destination: (req, file, cb) => {
what is cb?

2021-01-21 12:17 UTC, manoranjannayak commented on models/Image.js
> +  name: {
Done.

2021-01-21 12:18 UTC, manoranjannayak commented on controllers/gallery-controller.js
> +    Image.findByIdAndUpdate(id,{$set:{name: imageName, alt: imageAlt}},{new:true, upsert:true}).then((data)=>{
Sure. Done.

2021-01-21 12:19 UTC, manoranjannayak commented on controllers/gallery-controller.js
> +        res.send(data)
Done.

2021-01-21 12:20 UTC, manoranjannayak commented on controllers/gallery-controller.js
> +        res.send(data)
Done.

2021-01-21 12:22 UTC, manoranjannayak commented on routes/gallery-routes.js
> +router.patch("/:id", galleryController.patchGallery)
Done.

2021-01-21 12:42 UTC, manoranjannayak commented on views/gallery/gallery.ejs
> +  <% for (let data of datas) { %>
Done

2021-01-21 12:47 UTC, manoranjannayak commented on upload/index.js
> +    destination: (req, file, cb) => {
CB short for a callback function.
](https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/)]

2021-01-22 04:33 UTC, manoranjannayak commented on controllers/gallery-controller.js
> +        return res.redirect("gallery")
Done

2021-01-22 07:16 UTC, manoranjannayak commented on views/gallery/gallery.ejs
> +      action="/gallery?_csrf=<%= csrfToken %>"
Done.

2021-01-22 07:16 UTC, manoranjannayak commented on controllers/gallery-controller.js
> +        res.render("gallery/gallery.ejs",{datas})
Thanks

2021-01-24 19:22 UTC, merged